src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity=RestaurantPicture::class, mappedBy="restaurant", orphanRemoval=true)
     */
    private $restaurantPictures;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="restaurant", orphanRemoval=true)
     */
    private $reviews;

    public function __construct()
    {
        $this->createdAt=new \DateTime();
        //$this->setCreatedAt(new \DateTime());
        $this->restaurantPictures = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, RestaurantPicture>
     */
    public function getRestaurantPictures(): Collection
    {
        return $this->restaurantPictures;
    }

    public function addRestaurantPicture(RestaurantPicture $restaurantPicture): self
    {
        if (!$this->restaurantPictures->contains($restaurantPicture)) {
            $this->restaurantPictures[] = $restaurantPicture;
            $restaurantPicture->setRestaurant($this);
        }

        return $this;
    }

    public function removeRestaurantPicture(RestaurantPicture $restaurantPicture): self
    {
        if ($this->restaurantPictures->removeElement($restaurantPicture)) {
            // set the owning side to null (unless already changed)
            if ($restaurantPicture->getRestaurant() === $this) {
                $restaurantPicture->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setRestaurant($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getRestaurant() === $this) {
                $review->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getAverageRating() : float
    {
        $sum = 0;
        $total = 0; 
        foreach($this->getReviews() as $review) {
            $sum += $review->getRating();
            $total++; 
        }
        return $sum/$total;
    }

    public function __toString() {
        return $this->name;
    }

}

src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\Restaurant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            //->add('createdAt')
            ->add('city')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;
use App\Entity\Restaurant;
use App\Entity\Review;
use App\Form\RestaurantType;
use App\Entity\City;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="list_restaurant")
     */
    public function restaurants(Request $request): Response
    {
        $data = $this->getDoctrine()->getRepository(Restaurant::class)->findAll();
        return $this->render('restaurant/restaurants.html.twig', [
            'restaurants' => $data,
        ]);
    }

    /**
     * @Route("/restaurant/create", name="restaurant_new")
     */
    public function create(Request $request)
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class,$restaurant);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($restaurant);
            $em->flush();
            $this->addFlash('notice','Submitted Successfully');
            return $this->redirectToRoute('list_restaurant');
        }
        return $this->render('restaurant/create.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/restaurants/{id}", name="app_search")
     */
    public function chercher_restaurant(Request $request, $id): Response
    {
        $data = $this->getDoctrine()->getRepository(Restaurant::class)->find($id);
        return $this->render('restaurant/find.html.twig', [
            'restaurants' => $data,
        ]);
    }

    /**
     * @Route("/find")
     */
    public function afficherRest()
    {
        return $this->render('restaurant/restaurants.html.twig', [
            'restaurants' => $this->getDoctrine()->getRepository(Restaurant::class)->findLastSElements(),
        ]);
    }

    /**
     * @Route("/details/{id}", name="detailrestaurant")
     */
    public function DetailsRest($id)
    {
        return $this->render('restaurant/listerdetails.html.twig', [
            'restaurants' => $this->getDoctrine()->getRepository(Restaurant::class)->detailsRest($id),
        ]);
    }

    /**
     * @Route("/moyen/{id}")
     */
    public function afficheMoyen($id)
    {
        return $this->render('restaurant/moyen.html.twig', [
            'restaurants' => $this->getDoctrine()->getRepository(Restaurant::class)->restaurantrating($id),
        ]);
    }

    /**
    * @Route("/meilleur", methods={"GET"})
    */
    public function Meilleur()
    {
        $tenBestRestaurantsId = $this->getDoctrine()->getRepository(Review::class)->findBestTreeRatings();

        $tenBestRestaurants = array_map(function($data) {
            return $this->getDoctrine()->getRepository(Restaurant::class)->find($data['restaurantId']);
        }, $tenBestRestaurantsId);
        $tenBestRestaurants = [];
        foreach($tenBestRestaurantsId as $data) {
            $tenBestRestaurants[] = $this->getDoctrine()->getRepository(Restaurant::class)->find($data['restaurantId']);
        }
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $tenBestRestaurants,
        ]);
    }

    /**
    * @Route("/bestRe", methods={"GET"})
    */
    public function BestR()
    {
        $tenBestRestaurantsId = $this->getDoctrine()->getRepository(Review::class)->findBestRatings();

        $tenBestRestaurants = array_map(function($data) {
            return $this->getDoctrine()->getRepository(Restaurant::class)->find($data['restaurantId']);
        }, $tenBestRestaurantsId);
        $tenBestRestaurants = [];
        foreach($tenBestRestaurantsId as $data) {
            $tenBestRestaurants[] = $this->getDoctrine()->getRepository(Restaurant::class)->find($data['restaurantId']);
        }
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $tenBestRestaurants,
        ]);
    }




}

templates/restaurant/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <div class="row">
            <h3 class="mt">Create Restaurant</h3>
            {% for message in app.flashes('notice') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="col">
                {{ form_start(form) }}
                    <div class="form-group">
                        {{form_label(form.name)}}
                        {{ form_widget(form.name,{'attr':{'class':'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{form_label(form.description)}}
                        {{ form_widget(form.description,{'attr':{'class':'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.city) }}
                        {{ form_widget(form.city,{'attr':{'class':'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        <button class="btn btn-info">Submit</button>
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/restaurant/find.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des restaurants{% endblock %}

{% block body %}
    <div class="container">
        <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Date</th>
            
        </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">{{ restaurants.id }}</th>
                <td>{{ restaurants.name }}</td>
                <td>{{ restaurants.description }}</td>
                <td>{{ restaurants.getCreatedAt()|date('Y-m-d') }}</td>
                
            </tr>
        </tbody>
        </table>
    </div>
{% endblock %}

templates/restaurant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des restaurants{% endblock %}

{% block body %}

    <div class="container">
        <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Date</th>
        </tr>
        </thead>
        <tbody>
        {% for restaurant in restaurants %}
            <tr>
                <th scope="row">{{ restaurant.id }}</th>
                <td>{{ restaurant.name }}</td>
                <td>{{ restaurant.description }}</td>
                <td>{{ restaurant.getCreatedAt()|date('Y-m-d') }}</td>
                <td>{{ restaurant.averageRating | number_format(2, ',') }}</td>
                
                
            </tr>
        {% endfor %}
        </tbody>
        </table>

{% endblock %}

templates/restaurant/listerdetails.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des restaurants{% endblock %}

{% block body %}
    <div class="container">
        <table class="table">
        <thead>
        <tr>
            <th scope="col">Message</th>
            <th scope="col">Rating</th>
            <th scope="col">Name city</th>
            
            
            
        </tr>
        </thead>
        <tbody>
            <tr>
                
                <td>{{ restaurants[0].reviewmessage }}</td>
                <td>{{ restaurants[0].reviewrating }}</td>
                <td>{{ restaurants[0].cityname }}</td>
                
            </tr>
        </tbody>
        </table>
        
    </div>
{% endblock %}

templates/restaurant/moyen.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des restaurants{% endblock %}

{% block body %}
    <div class="container">
        <table class="table">
        <thead>
        <tr>
            <th scope="col">Moyenne</th>
        </tr>
        </thead>
        <tbody>
        {% for data in restaurants %}
            <tr>
                <td>{{restaurants[0][1]}}</td>   
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}

templates/restaurant/restaurants.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des restaurants{% endblock %}

{% block body %}
    
        <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Date</th>
            <th scope="col">Details</th>
            
             
            
        </tr>
        </thead>
        <tbody>
        {% for data in restaurants %}
            <tr>
                <th scope="row">{{ data.id }}</th>
                <td>{{ data.name }}</td>
                <td>{{ data.description }}</td>
                <td>{{ data.getCreatedAt()|date('Y-m-d') }}</td>
                <td><a href="http://127.0.0.1:40443/details/{{data.id}}">Details</a></td>
                
            </tr>
        {% endfor %}
        </tbody>
        </table>
        
    </div>
{% endblock %}